import { Component, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';
import { BaseItem } from '../../../definitions/models/baseItem.model';
import { FormBuilderService } from '../../../services/form-builder.service';

@Component({
  selector: 'lib-dyn-table',
  templateUrl: './dyn-table.component.html',
  styleUrls: ['./dyn-table.component.css']
})
export class DynTableComponent implements OnInit, OnChanges{

  @Input() formBuilder : FormBuilderService;
  @Input() data : Object[];

  actionsId = 'actions';
  dataSource : MatTableDataSource<Object> = new MatTableDataSource<Object>();
  collectionItems : BaseItem[];
  constructor(
  ) { }

  ngOnChanges(changes: SimpleChanges): void {
    this.dataSource = new MatTableDataSource<Object>(tmpdata);
  }

  ngOnInit() {
     this.collectionItems = this.formBuilder.collectionTableItems;
    this.buildColumnsNames();
  }

  displayedColumns : string[] = []

  buildColumnsNames(){
    this.displayedColumns = this.collectionItems
      .filter(x=>x.visible)
      .sort(x => x.order)
      .map(x=>x.id);
    
    if(this.formBuilder.enableActions)
      this.displayedColumns.push(this.actionsId);
  }

  getTitle(columnName:string){
    if(this.actionsId == columnName)
      return 'Acciones';

    return this.collectionItems.find(x=>x.id==columnName).displayName;
  }

  getData(columnName:string){
    return '';
  }

  displayData(element:any, column:string){
      var displayData = this.collectionItems.find(x=>x.id == column).recreateDisplay(element[column]);
     return displayData;
  }

}


export const tmpdata = 
[
  {
     "transactionId":46,
     "sisAccount":"315007164",
     "userOwnerId":"annel.ibarra15@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":4,
     "campusId":"15",
     "campusName":"TOLUCA",
     "studentCampusId":"15",
     "studentCampusName":"TOLUCA",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"IBARRA ROJAS ANEL ADYMA",
     "transactionStatus":{
        "statusId":4,
        "statusName":"Pagada",
        "message":"La solicitud ha sido pagada",
        "color":"",
        "procedureID":1,
        "orderStatus":2,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Pago"
     },
     "trasactionsLogs":[
        {
           "id":110,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-11T15:41:27.53",
           "transactionId":46,
           "userChangeId":"gabriela.deleonh@laureate.mx",
           "transactionStatus":null
        },
        {
           "id":143,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-11T18:11:26.46",
           "transactionId":46,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":144,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-11T18:16:19.343",
           "transactionId":46,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":145,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-11T18:21:00.273",
           "transactionId":46,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":146,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-11T18:21:51.013",
           "transactionId":46,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":147,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-11T18:29:03.287",
           "transactionId":46,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":148,
           "statusId":4,
           "actualState":true,
           "date":"2019-02-11T18:31:26.633",
           "transactionId":46,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-11T15:41:27.523",
     "userRequesterId":"gabriela.deleonh@laureate.mx",
     "documentName":"Constancia de alumno no inscrito",
     "userRequesterType":"Admin",
     "ignoreTransaction":true,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":54,
     "sisAccount":"316000939",
     "userOwnerId":"claudia.kumazawa@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":4,
     "campusId":"01",
     "campusName":"CUITLAHUAC",
     "studentCampusId":"01",
     "studentCampusName":"CUITLAHUAC",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"HERNANDEZ ANGUIANO ANDREA ",
     "transactionStatus":{
        "statusId":4,
        "statusName":"Pagada",
        "message":"La solicitud ha sido pagada",
        "color":"",
        "procedureID":1,
        "orderStatus":2,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Pago"
     },
     "trasactionsLogs":[
        {
           "id":164,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-12T13:01:25.047",
           "transactionId":54,
           "userChangeId":"gabriela.deleonh@laureate.mx",
           "transactionStatus":null
        },
        {
           "id":166,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-12T13:07:01.783",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":167,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-12T13:27:53.99",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":170,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-12T15:57:48.353",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":171,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-12T15:58:24.357",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":172,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-12T16:07:56.077",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":173,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-12T16:08:00.1",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":178,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-12T17:37:18.24",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":179,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-12T17:37:37.88",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":182,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-12T17:52:42.543",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":183,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-12T17:52:46.733",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":184,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-12T18:24:56.72",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":185,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-12T18:25:17.143",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":187,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T11:57:02.41",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":188,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T12:03:57.41",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":189,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T12:41:25.89",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":190,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T13:17:05.06",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":191,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T13:20:44.263",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":192,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T13:22:30.78",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":193,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T13:52:14.313",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":194,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T13:53:14.853",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":196,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T14:08:01.643",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":197,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T14:09:40.32",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":200,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T15:32:14.247",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":201,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T16:29:22.91",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":202,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T16:30:07.737",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":203,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T16:38:33.847",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":204,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T16:39:22.793",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":205,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T16:46:30.077",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":206,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T16:49:25.457",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":207,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T16:49:57.037",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":208,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T17:05:38.353",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":209,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T17:06:01.303",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":210,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T17:18:56.01",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":211,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T17:19:19.68",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":212,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T17:23:02.913",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":213,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T17:23:25.57",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":214,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T17:25:03.84",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":215,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T17:25:22.663",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":216,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T17:27:28.66",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":217,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T17:27:49.45",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":218,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-13T17:28:50.307",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":219,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-13T17:29:09.82",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":228,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T10:08:11.833",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":229,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T10:10:03.423",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":230,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T10:19:14.813",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":231,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T10:19:49.867",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":232,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T10:35:30.897",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":233,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T10:35:52.547",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":234,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T10:45:18.297",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":235,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T10:46:05.777",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":238,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T12:14:01.093",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":239,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T12:14:31.29",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":240,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T12:19:36.413",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":241,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T12:19:49.693",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":242,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T12:28:16.327",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":243,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T12:28:44.693",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":244,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T12:48:52.367",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":245,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T12:49:08.013",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":246,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T13:10:18.297",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":247,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T13:11:23.417",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":248,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T13:18:14.28",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":249,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T13:29:15.17",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":250,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T13:30:12.527",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":251,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T13:39:43.487",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":252,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T13:57:03.483",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":253,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T14:09:07.373",
           "transactionId":54,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":254,
           "statusId":6,
           "actualState":true,
           "date":"2019-02-14T14:10:45.443",
           "transactionId":54,
           "userChangeId":"",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-12T13:01:24.943",
     "userRequesterId":"gabriela.deleonh@laureate.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Admin",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":70,
     "sisAccount":"316000939",
     "userOwnerId":"andrea.hernandez16@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":6,
     "campusId":"16",
     "campusName":"LEON",
     "studentCampusId":"16",
     "studentCampusName":"LEON",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"HERNANDEZ ANGUIANO ANDREA ",
     "transactionStatus":{
        "statusId":6,
        "statusName":"Entregada",
        "message":"Se ha enviado a su correo la constancia",
        "color":"green",
        "procedureID":1,
        "orderStatus":3,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Entrega"
     },
     "trasactionsLogs":[
        {
           "id":257,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-14T15:33:55.283",
           "transactionId":70,
           "userChangeId":"gabriela.deleonh@laureate.mx",
           "transactionStatus":null
        },
        {
           "id":258,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T15:36:54.333",
           "transactionId":70,
           "userChangeId":"andrea.hernandez16@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":259,
           "statusId":6,
           "actualState":true,
           "date":"2019-02-14T15:37:28.413",
           "transactionId":70,
           "userChangeId":"",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-14T15:33:55.18",
     "userRequesterId":"gabriela.deleonh@laureate.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Admin",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":72,
     "sisAccount":"87216382",
     "userOwnerId":"claudia.kumazawa@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":6,
     "campusId":"03",
     "campusName":"CUITLAHUAC",
     "studentCampusId":"03",
     "studentCampusName":"CUITLAHUAC",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"KUMAZAWA CERDA CLAUDIA HIROKO",
     "transactionStatus":{
        "statusId":6,
        "statusName":"Entregada",
        "message":"Se ha enviado a su correo la constancia",
        "color":"green",
        "procedureID":1,
        "orderStatus":3,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Entrega"
     },
     "trasactionsLogs":[
        {
           "id":268,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-14T17:14:45.147",
           "transactionId":72,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":269,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T17:15:05.313",
           "transactionId":72,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":270,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-14T17:15:08.783",
           "transactionId":72,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":271,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-14T17:15:16.53",
           "transactionId":72,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":299,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T10:07:58.65",
           "transactionId":72,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":301,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T10:26:28.967",
           "transactionId":72,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":303,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T11:18:17.693",
           "transactionId":72,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":306,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T12:03:06.427",
           "transactionId":72,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":310,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T13:01:10.097",
           "transactionId":72,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":311,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T13:02:33.857",
           "transactionId":72,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":313,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T13:26:52.097",
           "transactionId":72,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":314,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T13:28:49.29",
           "transactionId":72,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":315,
           "statusId":6,
           "actualState":true,
           "date":"2019-02-18T13:43:03.297",
           "transactionId":72,
           "userChangeId":"",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-14T17:14:45.05",
     "userRequesterId":"claudia.kumazawa@my.unitec.edu.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Student",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":96,
     "sisAccount":"87216382",
     "userOwnerId":"claudia.kumazawa@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":6,
     "campusId":"03",
     "campusName":"CUITLAHUAC",
     "studentCampusId":"03",
     "studentCampusName":"CUITLAHUAC",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"KUMAZAWA CERDA CLAUDIA HIROKO",
     "transactionStatus":{
        "statusId":6,
        "statusName":"Entregada",
        "message":"Se ha enviado a su correo la constancia",
        "color":"green",
        "procedureID":1,
        "orderStatus":3,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Entrega"
     },
     "trasactionsLogs":[
        {
           "id":317,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-18T14:01:26.217",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":318,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T14:02:54.607",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":319,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T14:03:55.82",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":320,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T14:05:18.763",
           "transactionId":96,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":321,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T14:14:40.703",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":322,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T14:17:44.71",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":323,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T14:21:10.903",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":324,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T14:21:21.703",
           "transactionId":96,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":330,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T15:50:09.6",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":331,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T15:50:24.847",
           "transactionId":96,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":333,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T15:53:17.937",
           "transactionId":96,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":340,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T17:02:27.72",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":341,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T17:02:41.69",
           "transactionId":96,
           "userChangeId":"",
           "transactionStatus":null
        },
        {
           "id":342,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-18T17:09:46.02",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":343,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-18T17:11:29.05",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":344,
           "statusId":6,
           "actualState":true,
           "date":"2019-02-18T17:11:36.96",
           "transactionId":96,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-18T14:01:26.213",
     "userRequesterId":"claudia.kumazawa@my.unitec.edu.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Student",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":127,
     "sisAccount":"87216382",
     "userOwnerId":"claudia.kumazawa@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":6,
     "campusId":"03",
     "campusName":"CUITLAHUAC",
     "studentCampusId":"03",
     "studentCampusName":"CUITLAHUAC",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"KUMAZAWA CERDA CLAUDIA HIROKO",
     "transactionStatus":{
        "statusId":6,
        "statusName":"Entregada",
        "message":"Se ha enviado a su correo la constancia",
        "color":"green",
        "procedureID":1,
        "orderStatus":3,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Entrega"
     },
     "trasactionsLogs":[
        {
           "id":384,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-19T11:57:22.727",
           "transactionId":127,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":385,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-19T11:58:51.563",
           "transactionId":127,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":386,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-19T12:27:56.953",
           "transactionId":127,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":387,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-19T12:28:04.03",
           "transactionId":127,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":474,
           "statusId":6,
           "actualState":true,
           "date":"2019-02-20T17:28:21.253",
           "transactionId":127,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-19T11:57:22.723",
     "userRequesterId":"claudia.kumazawa@my.unitec.edu.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Student",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":170,
     "sisAccount":"315021949",
     "userOwnerId":"hector.vicente15@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":4,
     "campusId":"15",
     "campusName":"TOLUCA",
     "studentCampusId":"15",
     "studentCampusName":"TOLUCA",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"VICENTE ANDRADE HECTOR ALEJANDRO",
     "transactionStatus":{
        "statusId":4,
        "statusName":"Pagada",
        "message":"La solicitud ha sido pagada",
        "color":"",
        "procedureID":1,
        "orderStatus":2,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Pago"
     },
     "trasactionsLogs":[
        {
           "id":838,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-25T17:39:57.047",
           "transactionId":170,
           "userChangeId":"hector.vicente15@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":842,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-25T17:49:38.983",
           "transactionId":170,
           "userChangeId":"hector.vicente15@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":843,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-25T17:50:08.717",
           "transactionId":170,
           "userChangeId":"hector.vicente15@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":844,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-25T17:53:05.437",
           "transactionId":170,
           "userChangeId":"hector.vicente15@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":845,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-25T17:53:30.19",
           "transactionId":170,
           "userChangeId":"hector.vicente15@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":846,
           "statusId":4,
           "actualState":true,
           "date":"2019-02-25T18:09:42.58",
           "transactionId":170,
           "userChangeId":"hector.vicente15@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":443,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-20T12:54:41.277",
           "transactionId":170,
           "userChangeId":"hector.vicente15@my.unitec.edu.mx",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-20T12:54:41.257",
     "userRequesterId":"hector.vicente15@my.unitec.edu.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Student",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":191,
     "sisAccount":"315023502",
     "userOwnerId":"emma.fuentes15@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":6,
     "campusId":"15",
     "campusName":"TOLUCA",
     "studentCampusId":"15",
     "studentCampusName":"TOLUCA",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"FUENTES VENTURA EMMA LAURA",
     "transactionStatus":{
        "statusId":6,
        "statusName":"Entregada",
        "message":"Se ha enviado a su correo la constancia",
        "color":"green",
        "procedureID":1,
        "orderStatus":3,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Entrega"
     },
     "trasactionsLogs":[
        {
           "id":477,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-20T18:08:28.973",
           "transactionId":191,
           "userChangeId":"esanchezl15@qa.tutor.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":607,
           "statusId":6,
           "actualState":false,
           "date":"2019-02-21T18:34:09.14",
           "transactionId":191,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":608,
           "statusId":6,
           "actualState":true,
           "date":"2019-02-21T18:42:19.55",
           "transactionId":191,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-20T18:08:28.91",
     "userRequesterId":"esanchezl15@qa.tutor.unitec.edu.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Tutor",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":196,
     "sisAccount":"04326363",
     "userOwnerId":"dulce.delcarmen@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":6,
     "campusId":"03",
     "campusName":"CUITLAHUAC",
     "studentCampusId":"03",
     "studentCampusName":"CUITLAHUAC",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"DEL CARMEN MORENO DULCE CARMINA",
     "transactionStatus":{
        "statusId":6,
        "statusName":"Entregada",
        "message":"Se ha enviado a su correo la constancia",
        "color":"green",
        "procedureID":1,
        "orderStatus":3,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Entrega"
     },
     "trasactionsLogs":[
        {
           "id":484,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-20T18:22:16.24",
           "transactionId":196,
           "userChangeId":"dulce.delcarmen@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":482,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-20T18:21:01.273",
           "transactionId":196,
           "userChangeId":"dulce.delcarmen@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":488,
           "statusId":6,
           "actualState":true,
           "date":"2019-02-20T18:32:23.083",
           "transactionId":196,
           "userChangeId":"dulce.delcarmen@my.unitec.edu.mx",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-20T18:21:01.27",
     "userRequesterId":"dulce.delcarmen@my.unitec.edu.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Student",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  },
  {
     "transactionId":197,
     "sisAccount":"87216382",
     "userOwnerId":"claudia.kumazawa@my.unitec.edu.mx",
     "procedureId":1,
     "statusId":6,
     "campusId":"03",
     "campusName":"CUITLAHUAC",
     "studentCampusId":"03",
     "studentCampusName":"CUITLAHUAC",
     "schoolId":null,
     "schoolName":null,
     "careerId":null,
     "careerName":null,
     "grade":null,
     "studentName":"KUMAZAWA CERDA CLAUDIA HIROKO",
     "transactionStatus":{
        "statusId":6,
        "statusName":"Entregada",
        "message":"Se ha enviado a su correo la constancia",
        "color":"green",
        "procedureID":1,
        "orderStatus":3,
        "stepPath":"service-window/supporting-document/finishrequest",
        "statusNameTracker":"Entrega"
     },
     "trasactionsLogs":[
        {
           "id":483,
           "statusId":2,
           "actualState":false,
           "date":"2019-02-20T18:21:42.11",
           "transactionId":197,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":485,
           "statusId":4,
           "actualState":false,
           "date":"2019-02-20T18:22:37.213",
           "transactionId":197,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        },
        {
           "id":486,
           "statusId":6,
           "actualState":true,
           "date":"2019-02-20T18:23:01.2",
           "transactionId":197,
           "userChangeId":"claudia.kumazawa@my.unitec.edu.mx",
           "transactionStatus":null
        }
     ],
     "requestDate":"2019-02-20T18:21:42.1",
     "userRequesterId":"claudia.kumazawa@my.unitec.edu.mx",
     "documentName":"Constancia de alumno inscrito",
     "userRequesterType":"Student",
     "ignoreTransaction":false,
     "additionalData":null,
     "transactionTracker":null
  }
]
